#!/bin/bash
source /root/mybackup/vars
backup_status (){
echo "$1" | mutt -s "Backup allert" -- allerting@inbox.ru
echo "$1" >> "$backup_logs"
}
check_availability_app (){
    if [ ! "$(which $1)" ];
        then
            echo "The mysqldump utility is missing from the system" >> "/root/mybackup/logs.txt" && exit 1
    fi
}
creating_backup (){
    /usr/bin/mysqldump --single-transaction -u"$1" -p"$2" -h"$3" zabbix > "$4$5".sql
}

check_backup_creating (){
    if [ $1 -eq 0 ];
        then
            gzip -f "$2$3".sql
            backup_status "$ok_messadge"
        else
            backup_status "$err_messadge" $$ exit 2
    fi
}
check_and_delete_backups (){
    find $4 -type f -ctime +$2 -delete
    if [ $1 -eq 0 ];
        then
            echo "Backups older than $2 days have been deleted"  >> "$3" && exit 0
        else
            echo "Error deleting old backups"  >> "$3" && exit 3
    fi
}
echo "--------------------------$backup_time--------------------------" >> "$backup_logs"
check_availability_app "mysqldump"
creating_backup "$user" "$password" "$host" "$backup_path" "$backup_name"
check_backup_creating "$?" "$backup_path" "$backup_name"
check_and_delete_backups "$?" "$days_of_removal" "$backup_logs" "$backup_path"